// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDySW0LszelTT7PHtMWCY-_pKd_KutNRjg',
    appId: '1:924148622723:web:6d8f9fb4899090a3cc02b6',
    messagingSenderId: '924148622723',
    projectId: 'chatapp-ebc70',
    authDomain: 'chatapp-ebc70.firebaseapp.com',
    storageBucket: 'chatapp-ebc70.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_s525nJYSnS9-JwVO1sPvhJqgC0JUz10',
    appId: '1:924148622723:android:1e8a184d353cd119cc02b6',
    messagingSenderId: '924148622723',
    projectId: 'chatapp-ebc70',
    storageBucket: 'chatapp-ebc70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD994_L4DujwFN1ReMU_p54ZoQ2503KWWQ',
    appId: '1:924148622723:ios:3c892c72e98c3b86cc02b6',
    messagingSenderId: '924148622723',
    projectId: 'chatapp-ebc70',
    storageBucket: 'chatapp-ebc70.appspot.com',
    iosClientId: '924148622723-v5cmg253jj4bokvv31cnuse0ekepkvol.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
